@startuml

Rasterizer->Pipeline:consumer
Pipeline->Rasterizer:DoDraw
Rasterizer->Rasterizer:DrawToSurface

Rasterizer->GPUSurfaceGL:AcquireFrame
Rasterizer->CompositorContext:AcquireFrame
Rasterizer->ScopedFrame:Raster
ScopedFrame->LayerTree:Preroll
ScopedFrame->LayerTree:Paint
Rasterizer->SurfaceFrame:Submit
SurfaceFrame->SurfaceFrame:PerformSubmit
SurfaceFrame->GPUSurfaceGL:PresentSurface
GPUSurfaceGL->SkCanvas:flush
GPUSurfaceGL->AnddroidSurfaceGL:GLContextPresent
AnddroidSurfaceGL->AndroidContextGL:SwapBuffers

@enduml