@startuml

main->binding:runApp

binding->WidgetsFlutterBinding:ensureInitialized
WidgetsFlutterBinding->BindingBase:initInstances

BindingBase->WidgetsBinding:initInstances

WidgetsBinding->Window: nLocaleChanged\n onLocaleChanged\n navigation


BindingBase->RendererBinding:initInstances

RendererBinding->PipelineOwner:init
RendererBinding->Window: onMetricsChanged\n onTextScaleFactorChanged
RendererBinding->RenderView:scheduleInitialFrame

BindingBase->SemanticsBinding:initInstances
BindingBase->PaintingBinding:initInstances
PaintingBinding-> PaintingBinding:createImageCache

BindingBase->SchedulerBinding:initInstances

BindingBase->ServicesBinding:initInstances
ServicesBinding->Window:onPlatformMessage

BindingBase->GestureBinding:initInstances
BindingBase->Window:onPointerDataPacket

WidgetsFlutterBinding->WidgetsFlutterBinding:scheduleAttachRootWidget
WidgetsFlutterBinding->RenderObjectToWidgetAdapter:attachToRenderTree
RenderObjectToWidgetAdapter->Element:createElement

RenderObjectToWidgetAdapter->BuildOwner:buildScope
BuildOwner->RenderObjectToWidgetElement:mount
RenderObjectToWidgetElement->RenderObjectElement:mount
RenderObjectElement->Element:mount
RenderObjectToWidgetElement->RenderObjectToWidgetElement:_rebuild
RenderObjectToWidgetElement->Element:updateChild
Element->Element:inflateWidget


WidgetsFlutterBinding->SchedulerBinding:scheduleWarmUpFrame
SchedulerBinding->SchedulerBinding:handleBeginFrame
SchedulerBinding->SchedulerBinding:handleDrawFrame
SchedulerBinding->SchedulerBinding:resetEpoch()




@enduml
