@startuml

Title: state到触发pipleline开始渲染前调度过程

Widget->State:setState
State->Element:markNeedsBuild
Element->BuildOwner:scheduleBuildFor
BuildOwner->BuildOwner:onBuildScheduled
BuildOwner->WidgetsBinding:_handleBuildScheduled
WidgetsBinding->WidgetsBinding:ensureVisualUpdate
WidgetsBinding->SchedulerBinding:scheduleFrame
SchedulerBinding->WindowDart:scheduleFrame
WindowDart->Window:scheduleFrame
Window->Engine:scheduleFrame
Engine->Animator:RequestFrame
Animator->Animator:AwaitVSync
Animator->Animator:BeginFrame
Animator->Shell:OnAnimator\nBeginFrame
Shell->Engine:BeginFrame
Engine->RuntimeController:BeginFrame
RuntimeController->Window:BeginFrame
Window->WindowDart:BeginFrame
Window->UIDartState:FlushMicrotasksNow
Window->WindowDart:DrawFrame
WindowDart->SchedulerBinding:_handleDrawFrame
SchedulerBinding->RenderBinding:_handlePersistentFrameCallback
RenderBinding->PipelineOwner:flushLayout
RenderBinding->PipelineOwner:flushCompositingBits
RenderBinding->PipelineOwner:flushPaint
RenderBinding->RenderView:compositeFrame
RenderBinding->PipelineOwner:flushSemantics

@enduml
