@startmindmap

+ WEEX
-- 高可用
---  sdk指标
---- 性能
----- 可交互时间
------ 下载
------ 执行bundle
------ 数据请求
------ domdiff耗时
------ view耗时
----- 首屏时间
---- 稳定性
----- JSError
----- 白屏
----- 下载
----- 异常降级
--- 工具链支撑
---- 线下devtool analyzer
---- 卡发 ats
---- 线上高可用平台
--- 业务域
---- 平台
----- 斑马
----- air
---- 业务合作
----- 导购业务
----- 双十一会场
--- 经典案例
---- 白屏
----- 算法
------ 叶子节点
------ 特殊状态忽略
----- 排查手段
------ timeline
------ 链路state
------ 重点标记位
------ 业务打点
----- 价值
------ 多进程问题
------- IPC block问题
------- 多进程重启问题
------ 业务自身异常
------- JS错误
------- 发布异常
------- 数据错误
---- 可交互时间
----- 算法
------ 叶子节点
------ 边界值：不可见、8s
------ 业务特性：fixed
----- 准确度 
------ 视频逐帧 3%-15%
----- 价值
------ 阿里weex业务衡量标准
------ 双十一会场衡量体系
------ 小程序/架构native参考标准
---- 异常监控
----- 技术
------ 异常分类(js、白屏)
------ 降级采样预案
------ 告警策略
----- 价值
------ 双十一多次告警js错误(展示、交互异常)
------ 手淘p2故障监控
------ 90+app接入支持
++ weexCore
+++ IPC
++++ futext机制 cas
++++ mmap 共享内存
++++ 进程信号量通知
++++ 设计方案
+++++ 双向通信
+++++ 内存快控制（父偶子奇+futex）
+++++ 消息队列
+++++ bridge设计
++++++ 单双进程解耦、切换
+++ LayoutEngine
+++ bridge设计
++++ platform解耦
+++++ Android
+++++ iOS
+++++ windows、...
+++++ heron自绘制
++++ engine action解耦 
+++++ 二进制预编译方案（ast指令集）
+++ Android/iOS merge
+++ SandBox
++++ 全局污染
++++ JS vm 设计
+++ MutilThread
++++ UI 
++++ Core layout renderAction
++++ JS
++ JSRuntime
+++ BindingApi
++++ JSC
++++ V8
+++ ContextManager
+++ DomApi
+++ NativeModule

@endmindmap